CREATE TABLE books
(
	id VARCHAR(127) NOT NULL,
	Author LONGTEXT,
	LaunchDate DATETIME(6) NOT NULL,
	Price DECIMAL(65, 2) NOT NULL,
	Title LONGTEXT,
	PRIMARY KEY (id)
	
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;