USE dbperson;

CREATE  TABLE persons (
Id INT NOT NULL AUTO_INCREMENT,
FirstName VARCHAR(50) NULL DEFAULT NULL,
LastName VARCHAR(50) NULL DEFAULT NULL,
Address VARCHAR(50) NULL DEFAULT NULL,
Gender VARCHAR(50) NULL DEFAULT NULL,
PRIMARY KEY (Id)
)
ENGINE=INNODB
;     